<?php if ($this->tabs) echo $this->renderTabs($this->tabs) ?>
<legend><?php if ($this->domainList) echo $this->domainList;?><a href="<?php echo $this->backLink; ?>"><?php echo $this->domainName; ?></a></legend>
<p><?php echo $this->lmsg('domain.description'); ?></p>
<p>Bad Bot Blocker is <b><?php echo $this->currentStatus; ?></b>&nbsp;&nbsp;&nbsp;<?php echo $this->link_; ?></p>
<p><a href="javascript:checkData()"><?php echo $this->lmsg('domain.checkBlockedRequests'); ?></a></p>
<div id="logdata" style="white-space: pre; font-family: monospace;"></div>
<script>
//    Jsw.onReady(function() {
        var logdata = $('logdata');
        var resizeBlock = function() {
            var bodyHeight = $(document.body).getHeight();
            var blockTop = Position.cumulativeOffset(logdata).top;
            var blockBottom = $('footer-wrapper') ? $('footer-wrapper').getHeight() : 0;
            logdata.setStyle({ 'max-height': (bodyHeight - blockTop - blockBottom) + 'px' });
        };
        resizeBlock();
        Event.observe(window, 'resize', resizeBlock);

        var scrollBottom = function() {
            logdata.scrollTop = logdata.scrollHeight;
        };
        scrollBottom();
        function checkData() {
            $('logdata').innerHTML="";
            new Ajax.Request('<?php echo pm_Context::getActionUrl('index', 'check-domain') ?>', {
                    method: 'get',
                    parameters: { dom_id:<?php echo $this->dom_id;?>, site_id:<?php echo $this->site_id; ?> },
                    onCreate: function() {
                        inProgress = true;
                    },
                    onComplete: function() {
                        inProgress = false;
                    },
                    onSuccess: function(transport) {
                        var response = transport.responseText;
                        response = response.strip();

                        if (response.length>0) {
                                        content = "\n" + response;
                                        logdata.insert({ bottom: content });
                                        scrollBottom();
                        }
                    }
            })
        }

//    });

</script>
<?php if (isset($this->debug)) { echo '<pre>';var_dump($this->debug); echo '</pre>'; } ?>